### ISSUE TITLE
Support for external vault

### ISSUE THREAD

**Issue by monty16597** [hashicorp/vault-csi-provider#109]
Hey Team,

I have a use case where I want to manage a single vault server for multiple Kubernetes clusters running on different networks with their own CSI provider. I am wondering how the vault CSI provider is going to authenticate the external vault servers.

Do we need to provide vault auth token in the CRD resource itself? or need to configure vault CSI provider daemonset itself?
There are other parameters aswell as shown [here](https://github.com/hashicorp/vault-csi-provider/blob/master/internal/config/config.go#L33-L41).
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault:8200"
    roleName: ""
    objects: |
      - objectName: ""
        secretPath: ""
        secretKey: ""
```

**Comment by Crazyigor1987** [comment]
Hi @monty16597 ,

we're currently testing with external access like you do. We're facing the problem, that the CSI Vault Provider is currently not able to support multiple k8s cluster, because it is missing the auth path option. #111

**Comment by tomhjp** [comment]
Hi both, thanks for raising the question. The way to do this is to create one Kubernetes auth mount in Vault per Kubernetes cluster. Each will be under a different path, and you can then set [`vaultKubernetesMountPath`](https://www.vaultproject.io/docs/platform/k8s/csi/configurations#vaultkubernetesmountpath) in the CRD to target a non-default Kubernetes auth mount path. For example, based on your CRD:

```bash
vault auth enable -path=my-k8s-cluster kubernetes
```

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault:8200"
    vaultKubernetesMountPath: "my-k8s-cluster"
    roleName: ""
    objects: |
      - objectName: ""
        secretPath: ""
        secretKey: ""
```
