### ISSUE TITLE
EKS: Kubernetes 1.21 404 error

### ISSUE THREAD

**Issue by ArchiFleKs** [hashicorp/vault-csi-provider#110]
Hi, I'm currently running EKS 1.21 with secrets store CSI  as well as vault deployed with CSI and injector. I have updated the Kubernetes auth login to be compatible with the changes in 1.21 by settting the issuer which is somehting like this on EKS: `https://oidc.eks.eu-west-1.amazonaws.com/id/REDACTED123456`.

I have a vault cluster deployed in the vault namespace which is reachable at `http://vault.vault:8200`.

I have a KV store v2 with the following keys;

`ssv/operator`, inside I have to K/V, `PK = <data>`  and `SK=<data>`

I have a policy giving access to `ssv/*`  with `read` and `list`.

I have a vault role `ssv-node` binding service account `node` in namespace `ssv` giving access to the `ssv/` K/V store.

I have tested with an injector on a pod and it works fine.

I have the following secret provider class:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ssv-node
  namespace: ssv
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "ssv-node"
    objects: |
      - objectName: "operator-key"
        secretPath: "ssv/operator"
        secretKey: "SK"
    secretObjects:
    - data:
     - key: "SK"
       objectName: "operator-key"
     secretName: ssv-node
     type: Opaque
```

and then the following inside my pods:

```
    - csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ssv-node

...
      - mountPath: secrets                                                                                                                                                                                      
        name: secrets-store-inline  
```

In the pod description I get the following error:

```
 MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store object
s for pod ssv/node-0, err: rpc error: code = Unknown desc = error making mount request: couldn't read secret "operator-key": Error making API request.                                                           
                                                                                                        
URL: GET http://vault.vault:8200/v1/ssv/operator
Code: 404. Errors:                                 
```

**Comment by ArchiFleKs** [comment]
I seems to work with : 

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ssv-node
  namespace: ssv
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "ssv-node"
    objects: |
      - objectName: operator-key
        secretPath: ssv/data/operator
        secretKey: SK
  secretObjects:
  - data:
    - key: SK
      objectName: operator-key
    secretName: ssv-node
    type: Opaque
```
