### ISSUE TITLE
[OpenShift] CrashLoopBackOff when starting DS vault-csi-provider

### ISSUE THREAD

**Issue by devops-42** [hashicorp/vault-csi-provider#113]
Hi,

I tried to install Vault with CSI provider enabled on OpenShift using Helm and the following `values.yml`:

```
global:
  openshift: true
server:
  route: 
    enabled: true
ui:
  enabled: true
csi:
  enabled: true
injector:
  enabled: false
```

After deployment I checked which pods are running in the namespace. Only the vault pod was shown, but no pod for the vault-csi-provider. When looking at the events some SCC issues have occured, so I added the `privileged` SCC to get the pod started:

```
oc adm policy add-scc-to-user privileged system:serviceaccount:<vault-namespace>:vault-csi-provider
```

Now the pod could start, but immediately runs into an error state. The pod's log output is:

```
[ERROR] Error running provider: err="failed to listen on unix socket at /provider/vault.sock: listen unix /provider/vault.sock: bind: permission denied"
```

How could this be solved?

Thanks for your help in advance!
Cheers
Matthias
