### ISSUE TITLE
Renewing certs from PKI backend without restarting pod

### ISSUE THREAD

**Issue by technicaljones** [hashicorp/vault-csi-provider#116]
Hello, we want to migrate from the vault-injector to the vault-csi-provider to issue certificates which a service needs. We have a working example of doing this with a `SecretProviderClass` like below:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: k8s-certs
  namespace: monitoring
spec:
  parameters:
    objects: |
      - objectName: "kubernetes-key"
        secretPath: "k8s-ca/issue/monitoring"
        secretKey: "private_key"
        method: "PUT"
        secretArgs:
          common_name: monitoring
          ttl: 604800
    roleName: kubernetes
    vaultAddress: https://vaulturl:<port>
    vaultCACertPath: /vault/tls/dev.crt
    vaultKubernetesMountPath: kubernetes-auth
  provider: vault
```

This works fine however once the ttl is up the certs don't get renewed and the service fails. Is there a way to re-request these without restarting the pod? Will the auto rotation feature work for this?
