### ISSUE TITLE
Nested key reference in secretKey

### ISSUE THREAD

**Issue by edbighead** [hashicorp/vault-csi-provider#123]
Is there a way to specify a nested key in `secretKey` reference?
```bash
vault kv get -version=2 my-app/secrets | jq .data.data > temp.json
```
```json
{
  "VAR": "xxxx",
  "POSTGRES_BACKUP": {
    "PGDATABASE": "myapp",
    "PGHOST": "my-app.xxx123xxx.us-east-1.rds.amazonaws.com"
  }
}
```

Having the following block of `parameters` in `SecretProviderClass` 
```yaml
  parameters:
    roleName: my-role
    vaultKubernetesMountPath: kubernetes
    objects: |
      - objectName: pghost
        secretPath: my-app/data/secrets?version=2
        secretKey: POSTGRES_BACKUP.PGHOST
```
Results in error
```
failed to get secret content "POSTGRES_BACKUP.PGHOST" as string
```
