### ISSUE TITLE
Sync as Kubernetes Secret not working

### ISSUE THREAD

**Issue by domruf** [hashicorp/vault-csi-provider#125]
I have a SecretProviderClass and pod like the following. The secret is correctly mounted to /mnt/my-secrets and AFAIS there are no errors. But the kubernetes secret is not created and I therefore can't use it to set the environment variable.

I use
secrets-store-csi-driver helm chart 1.0.0
vault helm chart 0.18.0

Is there something missing or is this a bug?

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
spec:
  provider: vault
  secretObjects:
  - secretName: postgres-rootuser-from-vault
    type: Opaque
    data:
    - objectName: pgpass
      key: key
  parameters:
    vaultAddress: "https://myvaultserver.net/"
    roleName: myrole
    objects: |
      - objectName: pgpass
        secretPath: /mypath/POSTGRES_PASSWORD
        secretKey: key
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  serviceAccountName: myserviceaccount
  containers:
  - image: rancherlabs/swiss-army-knife
    name: testpod-sak
    command:
    - "sleep"
    - "3600"
    # env:
    # - name: pass_from_vault
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgres-rootuser-from-vault
    #       key: key
    volumeMounts:
    - name: my-secrets
      mountPath: "/mnt/my-secrets"
      readOnly: true
  volumes:
    - name: my-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-secrets"
```
