### ISSUE TITLE
JSON secret returned with full metadata 

### ISSUE THREAD

**Issue by Rudikza** [hashicorp/vault-csi-provider#140]
I have a JSON data structure in a v2 secret but when I try to create a file in my container the entire metadata is written into the file:

```
{"request_id":"9537b9d2-f99f-f60d-1ad1-c2ce7dc414e5","lease_id":"","lease_duration":0,"renewable":false,"data":{"data":{"connection_string":"string"}},"metadata":{"created_time":"2022-01-24T14:25:17.836353098Z","deletion_time":"","destroyed":false,"version":1}},"warnings":null}
```
Here are the details on my implementation:
```
CHART                           APP VERSION
secrets-store-csi-driver-1.0.1  1.0.1 
vault-0.19.0                    1.9.2  (hashicorp/vault-csi-provider:1.0.0)
```
I have tried many variations of secretKey. `.data`, `.Data`, `.Data.data` and even deleting the key completely

```
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-api-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: 'https://vault*****
    roleName: 'prod'
    objects: |
      - objectName: "web-secrets.json"
        secretPath: "prod/data/web/web-secrets.json"
        secretKey: ""
```

```
          volumeMounts:
            - name: vault-api-secrets-store-inline
              mountPath: "/usr/share/secrets/"
              readOnly: true
      volumes:
        - name: vault-api-secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: vault-api-secrets
```

As far as I can work out this should be fixed by https://github.com/hashicorp/vault-csi-provider/blob/1f4c3a26c578e71182cc430f7387bf94484b406f/internal/provider/provider.go#L155 but that is not the case.

Any ideas on what is happening here?
