### ISSUE TITLE
"aud" claim should be list, not string

### ISSUE THREAD

**Issue by sergiustheblack** [hashicorp/vault-csi-provider#231]
We use Vault Server external to EKS cluster with kubernetes auth with short-lived tokens (See https://developer.hashicorp.com/vault/docs/auth/kubernetes#use-the-vault-client-s-jwt-as-the-reviewer-jwt). Valid JWT contains the following part
```{
  "aud": [
    "https://kubernetes.default.svc"
  ],
...
}
```
In order to use external Vault with customized audience, audience claim must contain this string "https://kubernetes.default.svc".
When customizing audience, it is rewritten completely, what makes kubernetes auth with short-lived tokens broken.
Config:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-app
  namespace: app
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com:8200"
    audience: app
    roleName: app
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/some/path/secret"
        secretKey: "password"
```
Dumped JWT (partly).
```
{
  "aud": [
    "app"
  ],
...
}
```
Proposal: make audience list, not string. so, example config would be 
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-app
  namespace: app
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com:8200"
    audience:
      - app
      - "https://kubernetes.default.svc"
    roleName: app
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/some/path/secret"
        secretKey: "password"
```
